language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
git:
  depth: 3
cache: 
  diectories:
  - ~/.npm
script:
  - yarn build
deploy:
  provider: pages
  edge: true
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: build
  target-brach: gh-pages
  commit_message: 'Deploy Release'
  on:
    branch: master
