language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
script:
  - npm run deploy
git:
  depth: 3
deploy:
  provider: pages
  edge: true
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: /build
  target-brach: gh-pages
  commit_message: 'Deploy Release'
  on:
    branch: master
